### ISSUE TITLE
Add SonarCloud to Travis CI

### ISSUE THREAD

**Issue by Lobli** [BME-MIT-IET/DeNemOps-iet-2019#3]
How to :
https://docs.travis-ci.com/user/sonarcloud/

**Comment by Lobli** [comment]
https://stackoverflow.com/questions/30741762/travis-ci-command-gradlew-build-exited-with-1

**Comment by Lobli** [comment]
Először nem az App / build.gradle -be raktaam a plugint azért nem futott le a dolog.. Azt már javítottam, meg a fenti linken található megoldás hatására le is futott a dolog de még mindig van valami baja

**Comment by Lobli** [comment]
Most kiszedtem a token env vart a Travisből és elindítottam egy buildet, remélem nem az volt a baja

**Comment by Lobli** [comment]
<img width="853" alt="Screenshot 2019-05-05 at 15 53 13" src="https://user-images.githubusercontent.com/31661071/57195028-f0862980-6f4d-11e9-9442-f319051ab84f.png">
Nem az volt :/

**Comment by AkosRuszka** [comment]
Feltöltöttem egy módosítást hogy a sonarqube plugint szimpla 'apply plugin'-al adjuk meg. Hátha...

**Comment by Lobli** [comment]
Ezt már én is próbáltam, sajnos nem ez volt a hiba

**Comment by Lobli** [comment]
Így nem is találja meg a plugint

**Comment by AkosRuszka** [comment]
Igen, így jóval hamarabb elszáll.
Mergelek egyet a sonarcloud branchből, és megpróbálom azon alakítgatni. A "legelejétől" az első belinkelt How to alapján.

**Comment by Lobli** [comment]
Okés, ha tudok segíteni szólj

**Comment by AkosRuszka** [comment]
A megoldás az lett végül hogy a sonarqube-al kapcsolatos dolgokat a build.gradle-be és nem az app/build.gradle-be rakjuk, illetve a travis leíróját kiegészítettem a sonarcloud addons-al. 

Az első linkben leírtak alapján működik.

**Comment by Lobli** [comment]
Szuper 🙌
